provider:
  default:
    language: 8
  digitalocean:
    language: 8

sources:
  - src/**/*.java
  - pom.xml

binaries:
  - target/server-1.0.0.jar

files:
  - src/**/*.properties
  - src/**/*.xml 
  - src/**/*.jsp

deps:
  - java-1.8.0-openjdk

docker_pause: 10
