framework:
  website: struts.apache.org
  version: 2.5

build:
  - mvn clean package

binaries:
  - target/server-1.0.0.war

fixes:
  - mkdir -p /usr/share/java
  - wget https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.30.v20200611/jetty-runner-9.4.30.v20200611.jar -O /usr/share/java/jetty-runner.jar

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /usr/share/java/jetty-runner.jar --port 3000 /opt/web/target/server-1.0.0.war
