framework:
  website: struts.apache.org
  version: 2.5

build:
  - mvn clean package

binaries:
  - target/server-1.0.0.war
  - target/dependency/jetty-runner.jar

command: /usr/bin/java -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/target/dependency/jetty-runner.jar --port 3000 /opt/web/target/server-1.0.0.war
