framework:
  website: struts.apache.org
  version: 2.5

build:
  - mvn clean package

files:
  - target/struts2-1.0.war
  - target/benchmark-0.0.1-SNAPSHOT/WEB-INF/lib/jetty-runner-9.4.30.v20200611.jar

command: java  -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts  -jar /opt/web/target/benchmark-0.0.1-SNAPSHOT/WEB-INF/lib/jetty-runner-9.4.30.v20200611.jar --port 3000 target/struts2-1.0.war
